[versions]
# build tools
java = "17"
jacoco = "0.8.8"
kotlin = "1.9.22"

[libraries]
# build tools
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.1.0" }
# dependencies
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
# test dependencies
spock-core = { module = "org.spockframework:spock-core", version = "2.3-groovy-4.0" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.3" }
